// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  platformSidebar: [
    {
      type: "category",
      label: "Platform",
      link: {
        type: "generated-index",
        title: "Platform",
        slug: "/category/platform",
        keywords: [],
      },
      items: [
        {
          type: "autogenerated",
          dirName: "platform",
        },
      ],
    },
    {
      type: "category",
      label: "Agentic access with MCP",
      link: {
        type: "doc",
        id: "mcp/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "mcp",
        },
      ],
    },
  ],

  guidesSidebar: [
    {
      type: "category",
      label: "Deployment guides",
      link: {
        type: "generated-index",
        title: "Deployment guides",
        slug: "/category/guides/deployment",
        keywords: [],
      },
      items: [
        {
          type: "autogenerated",
          dirName: "guides/deployment",
        },
      ],
    },
    {
      type: "category",
      label: "Applications",
      link: {
        type: "generated-index",
        title: "Applications",
        slug: "/category/guides/apps",
        keywords: [],
      },
      items: [
        {
          type: "autogenerated",
          dirName: "guides/apps",
        },
      ],
    },
    {
      type: "category",
      label: "Operations",
      link: {
        type: "generated-index",
        title: "Operations",
        slug: "/category/guides/operations",
        keywords: [],
      },
      items: [
        {
          type: "autogenerated",
          dirName: "guides/operations",
        },
      ],
    },
  ],

  cliSidebar: [
    {
      type: "category",
      label: "Using the mittwald CLI",
      link: {
        type: "doc",
        id: "cli/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "cli/usage",
        },
      ],
    },
    {
      type: "category",
      label: "Examples",
      link: {
        type: "generated-index",
        title: "Examples",
        slug: "/category/cli-examples",
        keywords: [],
      },
      items: [
        {
          type: "autogenerated",
          dirName: "cli/examples",
        },
      ],
    },
    {
      type: "category",
      label: "Command reference",
      items: [
        {
          type: "autogenerated",
          dirName: "cli/reference",
        },
      ],
    },
  ],

  contributingSidebar: [
    {
      type: "category",
      label: "Contribution",
      link: {
        type: "doc",
        id: "contribution/index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "contribution",
        },
      ],
    },
  ],

  apiSidebar: [
    {
      type: "category",
      label: "Using the API",
      link: {
        type: "generated-index",
        title: "Using the API",
        slug: "/category/api",
        keywords: [],
      },
      items: [
        {
          type: "autogenerated",
          dirName: "api",
        },
      ],
    },
    {
      type: "category",
      label: "API Reference",
      items: require("./sidebar.reference.json"),
      link: {
        type: "doc",
        id: "reference/index",
      },
    },
    // {
    //   type: "category",
    //   label: "API Preview",
    //   items: require("./sidebar.preview.json"),
    //   link: {
    //     type: "doc",
    //     id: "preview/index",
    //   },
    // },
  ],
};

module.exports = sidebars;
