// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  platformSidebar: [
    {
      type: 'category',
      label: 'Platform',
      link: {
        type: "generated-index",
        title: "Platform",
        slug: "/category/platform",
        keywords: []
      },
      items: [{
        type: 'autogenerated',
        dirName: 'platform'
      }],
    },
  ],

  apiSidebar: [
    {
      type: 'category',
      label: 'Using the API',
      link: {
        type: "generated-index",
        title: "Using the API",
        slug: "/category/api",
        keywords: []
      },
      items: [{
        type: 'autogenerated',
        dirName: 'api'
      }],
    },
    {
      type: "category",
      label: "API Reference",
      items: require("./sidebar.reference.json"),
      link: {
        type: "generated-index",
        title: "API Reference",
        slug: "/category/reference",
        keywords: ["api-reference"]
      }
    }
  ],
};

module.exports = sidebars;
