### GET request to example server
GET https://api.github.com/repos/mittwald/cli/contents/docs?ref=master
Accept: application/vnd.github.object+json

### Get file
GET https://api.github.com/repos/mittwald/cli/contents/docs/app.md?ref=master
Accept: application/vnd.github.object+json


### Get latest release
GET https://api.github.com/repos/mittwald/cli/releases/latest